[2024-04-03T09:44:44.232+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_allocate_messages.delete_original_messages manual__2024-04-03T09:44:40.535367+00:00 [queued]>
[2024-04-03T09:44:44.266+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_allocate_messages.delete_original_messages manual__2024-04-03T09:44:40.535367+00:00 [queued]>
[2024-04-03T09:44:44.267+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-04-03T09:44:44.288+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): delete_original_messages> on 2024-04-03 09:44:40.535367+00:00
[2024-04-03T09:44:44.296+0000] {standard_task_runner.py:60} INFO - Started process 13060 to run task
[2024-04-03T09:44:44.302+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_allocate_messages', 'delete_original_messages', 'manual__2024-04-03T09:44:40.535367+00:00', '--job-id', '1259', '--raw', '--subdir', 'DAGS_FOLDER/dag_allocate_messages.py', '--cfg-path', '/tmp/tmpjj2ckc9h']
[2024-04-03T09:44:44.306+0000] {standard_task_runner.py:88} INFO - Job 1259: Subtask delete_original_messages
[2024-04-03T09:44:44.364+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_allocate_messages.delete_original_messages manual__2024-04-03T09:44:40.535367+00:00 [running]> on host af8488263d95
[2024-04-03T09:44:44.462+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='daniel' AIRFLOW_CTX_DAG_ID='dag_allocate_messages' AIRFLOW_CTX_TASK_ID='delete_original_messages' AIRFLOW_CTX_EXECUTION_DATE='2024-04-03T09:44:40.535367+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-03T09:44:40.535367+00:00'
[2024-04-03T09:44:44.463+0000] {logging_mixin.py:188} INFO - delete original messages
[2024-04-03T09:44:44.496+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_allocate_messages.py", line 145, in delete_original_messages
    message_ids += ti.xcom_pull(
TypeError: 'NoneType' object is not iterable
[2024-04-03T09:44:44.505+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_allocate_messages, task_id=delete_original_messages, execution_date=20240403T094440, start_date=20240403T094444, end_date=20240403T094444
[2024-04-03T09:44:44.521+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1259 for task delete_original_messages ('NoneType' object is not iterable; 13060)
[2024-04-03T09:44:44.555+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-03T09:44:44.575+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
