[2024-03-27T14:57:42.412+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_allocate_messages.select_and_allocate_messages manual__2024-03-27T14:42:34.175712+00:00 [queued]>
[2024-03-27T14:57:42.473+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_allocate_messages.select_and_allocate_messages manual__2024-03-27T14:42:34.175712+00:00 [queued]>
[2024-03-27T14:57:42.476+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 6
[2024-03-27T14:57:42.549+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): select_and_allocate_messages> on 2024-03-27 14:42:34.175712+00:00
[2024-03-27T14:57:42.573+0000] {standard_task_runner.py:60} INFO - Started process 14356 to run task
[2024-03-27T14:57:42.603+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_allocate_messages', 'select_and_allocate_messages', 'manual__2024-03-27T14:42:34.175712+00:00', '--job-id', '1093', '--raw', '--subdir', 'DAGS_FOLDER/dag_allocate_messages.py', '--cfg-path', '/tmp/tmp0zvjybw4']
[2024-03-27T14:57:42.621+0000] {standard_task_runner.py:88} INFO - Job 1093: Subtask select_and_allocate_messages
[2024-03-27T14:57:42.935+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_allocate_messages.select_and_allocate_messages manual__2024-03-27T14:42:34.175712+00:00 [running]> on host 932f824b7ebb
[2024-03-27T14:57:43.408+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='daniel' AIRFLOW_CTX_DAG_ID='dag_allocate_messages' AIRFLOW_CTX_TASK_ID='select_and_allocate_messages' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T14:42:34.175712+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-27T14:42:34.175712+00:00'
[2024-03-27T14:57:43.463+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-03-27T14:57:43.543+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_allocate_messages.py", line 21, in select_and_allocate_messages
    insert_message(cursor, "success_messages", message)
  File "/opt/airflow/dags/dag_allocate_messages.py", line 42, in insert_message
    cursor.execute(
ValueError: unsupported format character 'r' (0x72) at index 13
[2024-03-27T14:57:43.599+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_allocate_messages, task_id=select_and_allocate_messages, execution_date=20240327T144234, start_date=20240327T145742, end_date=20240327T145743
[2024-03-27T14:57:43.675+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1093 for task select_and_allocate_messages (unsupported format character 'r' (0x72) at index 13; 14356)
[2024-03-27T14:57:43.748+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-27T14:57:43.865+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
