[2024-03-13T08:52:20.447+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v05.postgres_to_s3 manual__2024-03-13T08:52:19.591195+00:00 [queued]>
[2024-03-13T08:52:20.459+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v05.postgres_to_s3 manual__2024-03-13T08:52:19.591195+00:00 [queued]>
[2024-03-13T08:52:20.459+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-03-13T08:52:20.478+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2024-03-13 08:52:19.591195+00:00
[2024-03-13T08:52:20.485+0000] {standard_task_runner.py:60} INFO - Started process 3700 to run task
[2024-03-13T08:52:20.494+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v05', 'postgres_to_s3', 'manual__2024-03-13T08:52:19.591195+00:00', '--job-id', '962', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpldo9fx9q']
[2024-03-13T08:52:20.497+0000] {standard_task_runner.py:88} INFO - Job 962: Subtask postgres_to_s3
[2024-03-13T08:52:20.562+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_hooks_v05.postgres_to_s3 manual__2024-03-13T08:52:19.591195+00:00 [running]> on host ce9c15199686
[2024-03-13T08:52:20.657+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Daniel' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks_v05' AIRFLOW_CTX_TASK_ID='postgres_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-03-13T08:52:19.591195+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-13T08:52:19.591195+00:00'
[2024-03-13T08:52:20.665+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2024-03-13T08:52:20.677+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-03-13T08:52:20.697+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_hooks.py", line 22, in postgres_to_s3
    with NamedTemporaryFile(mode="w", suffix=f"{ds_nodash}") as f:
NameError: name 'NamedTemporaryFile' is not defined
[2024-03-13T08:52:20.712+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_hooks_v05, task_id=postgres_to_s3, execution_date=20240313T085219, start_date=20240313T085220, end_date=20240313T085220
[2024-03-13T08:52:20.731+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 962 for task postgres_to_s3 (name 'NamedTemporaryFile' is not defined; 3700)
[2024-03-13T08:52:20.786+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-13T08:52:20.807+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
