[2024-03-12T14:26:52.541+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v03.get_sklearn scheduled__2021-11-01T00:00:00+00:00 [queued]>
[2024-03-12T14:26:52.579+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v03.get_sklearn scheduled__2021-11-01T00:00:00+00:00 [queued]>
[2024-03-12T14:26:52.580+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-12T14:26:52.709+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_sklearn> on 2021-11-01 00:00:00+00:00
[2024-03-12T14:26:52.749+0000] {standard_task_runner.py:60} INFO - Started process 16257 to run task
[2024-03-12T14:26:52.758+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v03', 'get_sklearn', 'scheduled__2021-11-01T00:00:00+00:00', '--job-id', '943', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmp4az7xz_d']
[2024-03-12T14:26:52.786+0000] {standard_task_runner.py:88} INFO - Job 943: Subtask get_sklearn
[2024-03-12T14:26:53.133+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_python_dependencies_v03.get_sklearn scheduled__2021-11-01T00:00:00+00:00 [running]> on host 26e63b1d0d39
[2024-03-12T14:26:53.577+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Daniel' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v03' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2021-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-11-01T00:00:00+00:00'
[2024-03-12T14:26:53.602+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 15, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2024-03-12T14:26:53.632+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dag_with_python_dependencies_v03, task_id=get_sklearn, execution_date=20211101T000000, start_date=20240312T142652, end_date=20240312T142653
[2024-03-12T14:26:53.690+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 943 for task get_sklearn (No module named 'sklearn'; 16257)
[2024-03-12T14:26:53.768+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-12T14:26:53.867+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
