[2024-03-25T15:16:19.915+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v05.postgres_to_s3 scheduled__2024-03-17T00:00:00+00:00 [queued]>
[2024-03-25T15:16:20.029+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v05.postgres_to_s3 scheduled__2024-03-17T00:00:00+00:00 [queued]>
[2024-03-25T15:16:20.038+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-03-25T15:16:20.157+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2024-03-17 00:00:00+00:00
[2024-03-25T15:16:20.202+0000] {standard_task_runner.py:60} INFO - Started process 213 to run task
[2024-03-25T15:16:20.265+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v05', 'postgres_to_s3', 'scheduled__2024-03-17T00:00:00+00:00', '--job-id', '977', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpoab4rabj']
[2024-03-25T15:16:20.295+0000] {standard_task_runner.py:88} INFO - Job 977: Subtask postgres_to_s3
[2024-03-25T15:16:20.623+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_hooks_v05.postgres_to_s3 scheduled__2024-03-17T00:00:00+00:00 [running]> on host 932f824b7ebb
[2024-03-25T15:16:21.371+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Daniel' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks_v05' AIRFLOW_CTX_TASK_ID='postgres_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-03-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-17T00:00:00+00:00'
[2024-03-25T15:16:21.475+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2024-03-25T15:16:21.555+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-03-25T15:16:21.615+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_hooks.py", line 17, in postgres_to_s3
    conn = hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.65.2), port 5432 failed: FATAL:  password authentication failed for user "***"

[2024-03-25T15:16:21.669+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_hooks_v05, task_id=postgres_to_s3, execution_date=20240317T000000, start_date=20240325T151619, end_date=20240325T151621
[2024-03-25T15:16:21.776+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 977 for task postgres_to_s3 (connection to server at "host.docker.internal" (192.168.65.2), port 5432 failed: FATAL:  password authentication failed for user "***"
; 213)
[2024-03-25T15:16:21.860+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-25T15:16:22.300+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
